# Generated by Django 4.2.1 on 2023-11-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_alter_gamebox_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebox',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gamebox',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamebox',
            name='ssh_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
