# Generated by Django 4.2.7 on 2023-11-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_alter_gamebox_description_alter_gamebox_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebox',
            name='team_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
