# Generated by Django 4.2.1 on 2023-11-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_alter_gamebox_description_alter_gamebox_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebox',
            name='challenge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
