# Generated by Django 3.2.12 on 2023-11-26 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_alter_gamebox_challenge_id'),
        ('challenge', '0004_alter_gamebox_team_id'),
    ]

    operations = [
    ]
