# Generated by Django 3.2.12 on 2023-11-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_merge_20231126_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebox',
            name='challenge_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
