# Generated by Django 4.2.1 on 2024-01-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_alter_gamebox_challenge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamebox',
            name='challenge_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
