# Generated by Django 4.2.1 on 2024-01-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_alter_gamebox_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebox',
            name='is_attacked',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='gamebox',
            name='is_down',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='gamebox',
            name='visible',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
