# Generated by Django 4.2.1 on 2024-02-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_alter_gamebox_is_attacked_alter_gamebox_is_down_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('ssh_port', models.PositiveIntegerField(blank=True, null=True)),
                ('ssh_user', models.CharField(blank=True, max_length=255, null=True)),
                ('ssh_password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'challenges',
            },
        ),
        migrations.RemoveField(
            model_name='gamebox',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='gamebox',
            name='port',
        ),
        migrations.RemoveField(
            model_name='gamebox',
            name='ssh_password',
        ),
        migrations.RemoveField(
            model_name='gamebox',
            name='ssh_port',
        ),
        migrations.RemoveField(
            model_name='gamebox',
            name='ssh_user',
        ),
    ]
