# Generated by Django 4.2.1 on 2024-02-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_challenge_remove_gamebox_ip_remove_gamebox_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='team_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
