# Generated by Django 5.0.1 on 2024-03-19 04:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0011_challenge_team_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='port',
            new_name='challenge_id',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='ip',
            new_name='challenge_name',
        ),
        migrations.RenameField(
            model_name='gamebox',
            old_name='challenge_name',
            new_name='ip',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='ssh_password',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='ssh_port',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='ssh_user',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='gamebox',
            name='description',
        ),
        migrations.AddField(
            model_name='challenge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gamebox',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamebox',
            name='ssh_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gamebox',
            name='ssh_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamebox',
            name='ssh_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gamebox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
