# Generated by Django 5.0.3 on 2024-03-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_name', models.CharField(max_length=50)),
                ('attacked_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attacked_team_id', models.PositiveIntegerField(blank=True, null=True)),
                ('challenge_id', models.PositiveIntegerField(blank=True, null=True)),
                ('game_box_id', models.PositiveIntegerField(blank=True, null=True)),
                ('attacker_team_id', models.PositiveIntegerField(blank=True, null=True)),
                ('round', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'action_log',
            },
        ),
        migrations.CreateModel(
            name='ActionTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_name', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('correct', models.BooleanField()),
                ('attacker_team_id', models.PositiveIntegerField(blank=True, null=True)),
                ('round', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
