# Generated by Django 4.2.7 on 2023-11-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_actionlog_delete_log_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_team', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('correct', models.BooleanField()),
            ],
        ),
    ]
