# Generated by Django 4.2.7 on 2023-11-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_alter_actionlog_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='attacker_team_id',
            field=models.CharField(max_length=50),
        ),
    ]
