# Generated by Django 4.2.7 on 2023-11-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_alter_actionlog_attacker_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
