# Generated by Django 4.2.7 on 2023-11-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_alter_actionlog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
