# Generated by Django 4.2.7 on 2023-11-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_actionlog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
