# Generated by Django 5.0.1 on 2024-01-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_alter_actionlog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
