# Generated by Django 5.0.1 on 2024-01-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0011_alter_actionlog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontry',
            name='attacker_team_id',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
