# Generated by Django 5.0.1 on 2024-01-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0013_actiontry_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontry',
            name='challenge_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actiontry',
            name='attacker_team_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
