# Generated by Django 5.0.1 on 2024-01-26 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0014_actiontry_challenge_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiontry',
            name='challenge_id',
        ),
    ]
