# Generated by Django 5.0.1 on 2024-01-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0015_remove_actiontry_challenge_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlog',
            name='name',
        ),
        migrations.AddField(
            model_name='actionlog',
            name='attacked_name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actionlog',
            name='attacker_name',
            field=models.CharField(default='hmm', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actiontry',
            name='attacker_name',
            field=models.CharField(default='hmm', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='attacker_team_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
