# Generated by Django 5.0.1 on 2024-01-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0016_remove_actionlog_name_actionlog_attacked_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlog',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='actiontry',
            name='submit_team',
        ),
        migrations.AddField(
            model_name='actionlog',
            name='attacked_team_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
