# Generated by Django 5.0.1 on 2024-02-21 06:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0017_remove_actionlog_team_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
