# Generated by Django 4.2.7 on 2023-11-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authinfo',
            name='team_id',
            field=models.CharField(max_length=50),
        ),
    ]
