# Generated by Django 4.2.7 on 2023-11-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_authinfo_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='authinfo',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
