# Generated by Django 5.0.1 on 2024-01-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_authinfo_challenge_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authinfo',
            name='challenge_name',
        ),
    ]
