# Generated by Django 5.0.1 on 2024-01-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_authinfo_challenge_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='authinfo',
            name='challenge_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
