# Generated by Django 5.0.1 on 2024-03-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_authinfo_challenge_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='authinfo',
            name='team_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
