# Generated by Django 5.0.3 on 2024-03-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('ctf_name', models.TextField()),
                ('flag_head', models.TextField()),
                ('round_time', models.IntegerField()),
                ('point_down', models.IntegerField()),
                ('point_attack', models.IntegerField()),
                ('point_base', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
