# Generated by Django 4.2.1 on 2024-01-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(verbose_name='시작 시각')),
                ('endtime', models.DateTimeField(verbose_name='종료 시각')),
                ('ctf_name', models.TextField(verbose_name='대회명')),
                ('flag_head', models.TextField(verbose_name='플래그 접두사')),
                ('round_time', models.IntegerField(verbose_name='각 라운드의 길이')),
                ('point_down', models.IntegerField(verbose_name='체크다운 포인트')),
                ('point_attack', models.IntegerField(verbose_name='어택 포인트')),
                ('point_base', models.IntegerField(verbose_name='베이스 포인트')),
                ('db_name', models.TextField(verbose_name='데이터베이스 이름')),
                ('db_port', models.IntegerField(verbose_name='데이터베이스 포트번호')),
                ('db_username', models.TextField(verbose_name='데이터베이스 유저네임')),
                ('db_password', models.TextField(verbose_name='데이터베이스 패스워드')),
            ],
        ),
    ]
