# Generated by Django 5.0.1 on 2024-02-15 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_config_ctf_name_alter_config_db_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
