# Generated by Django 5.0.1 on 2024-03-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_config_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='db_name',
        ),
        migrations.RemoveField(
            model_name='config',
            name='db_password',
        ),
        migrations.RemoveField(
            model_name='config',
            name='db_port',
        ),
        migrations.RemoveField(
            model_name='config',
            name='db_username',
        ),
    ]
