# Generated by Django 3.2.12 on 2023-11-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('team_id', models.PositiveIntegerField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
