# Generated by Django 3.2.12 on 2023-11-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20231106_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
