# Generated by Django 4.2.1 on 2024-03-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_team_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='secret_key',
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.PositiveIntegerField(blank=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
